apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
      - name: my-server
        image: fbdl.registry/poc/server:v1
        ports:
        - containerPort: 7777

